### ISSUE TITLE
java test runner run error

### ISSUE THREAD

**Issue by nihaoaeee** [exercism/java-test-runner#14]
Error: Running the contributed command: 'java.execute.workspaceCommand' failed..
use junit ,find Error ,-----Error: Running the contributed command: 'java.execute.workspaceCommand' failed..

**Comment by mirkoperillo** [comment]
@msomji any ideas ?

**Comment by msomji** [comment]
@nihaoaeee Can you provide more information regarding this error please.
What command was executed that resulted in this error, how to reproduce it, full stack trace.

**Comment by mirkoperillo** [comment]
I think this issue can be closed for missing detailed information
