### ISSUE TITLE
Java test runner does not complete before timeout

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java-test-runner#29]
I do not seem to have permissions needed to move https://github.com/exercism/exercism/issues/5806

I suspect there is too much time being lost compiling the code for some reason (even though there should be very minimal code compiling during these runs). Perhaps it is because it does the code generation for the test runner itself when it should only be needing to compile the tests and the student's code?

@msomji - any chance you can help take a look into this?

**Comment by msomji** [comment]
Hey @jmrunkle, I just responded in the thread on [exercism/exercism#5806](https://github.com/exercism/exercism/issues/5806)
From what I understand, though the test-runner's code does get compiled each time, the dependencies are already cached in the docker image's layer so that is probably not where we are losing time 🤞.  I am suspecting that the newer gradle version + the new jdk is causing the longer build times. 

I have suggested we just up the timeouts for lack of a better option.

**Comment by jmrunkle** [comment]
Increasing the timeouts will definitely help, but it means the servers can get more backed up handling those requests. That could be fine, but obviously has a real cost associated.

I'm curious if putting the test runner code itself in the same directory where we put the student test code is causing a double-compilation of the code for the test runner itself (like the code generation). Does that seem possible to you?

I am less concerned with finding out why it is slower now on the newer version of Gradle than why it is slow to begin with (12s was never "good" for a simple two-fer solution).

**Comment by msomji** [comment]
I am not sure if the double compilation is the culprit alone, because running `gradle clean build test` locally on the two-fer example all together takes ~2 seconds. But yes, totally agree that 12s was never good :,( 

I think we could put the test-runner code in the same dir as the student test code but would be surprised if that would make much of a difference.

I have been thinking if we should just scrap the test-runner entirely and just lean on parsing the gradle output of running the test via some shell shell scripts, might be faster than what we are doing right now, I just haven't had the time to spend thinking about what a solution like that would look like.

**Comment by jmrunkle** [comment]
> I think we could put the test-runner code in the same dir as the student test code but would be surprised if that would make much of a difference.

My point was more that the test-runner code itself looks like it gets compiled together with the student code.

> I have been thinking if we should just scrap the test-runner entirely and just lean on parsing the gradle output of running the test via some shell shell scripts, might be faster than what we are doing right now, I just haven't had the time to spend thinking about what a solution like that would look like.

I mean, I think we may need to do something more like that if we are going to fix #24 since we will need to add support for reading the source file contents to be able to add the `test_code`. Unless you have a clever solution for that in the existing setup.

**Comment by jmrunkle** [comment]
Tell me where I am going wrong in my understanding.

From the Dockerfile:

```
FROM pindar/jq as jq

FROM gradle:6.8.3-jdk11 

COPY --from=jq /usr/local/bin/jq /usr/local/bin/jq
RUN chmod +x /usr/local/bin/jq
```

Copy jq from pindar/jq into /usr/local/bin/jq, add execute permissions.

```
COPY lib/build.gradle /opt/test-runner/lib/build.gradle

COPY lib/buildSrc/build.gradle /opt/test-runner/lib/buildSrc/build.gradle
COPY lib/buildSrc/src /opt/test-runner/lib/buildSrc/src
```

These read basically like English copying these two build.gradle files and the src directory (which actually contains all of the test runner code).

```
WORKDIR /opt/test-runner
RUN cd /opt/test-runner/lib/buildSrc; \
    gradle clean build; \
```

Use /opt/test-runner as the working directory, but we immediately cd to /otp/test-runner/lib/buildSrc (where the test runner code lives) and then call gradle clean build.

```
    mkdir /opt/test-runner/gradle; \
    cp -r ~/.gradle/ /opt/test-runner/gradle/.gradle/; \
```

Next we make a directory and copy ~/.gradle/ into it.

```
    unlink /root/.gradle; \
    ln -s /opt/test-runner/gradle/.gradle /root/.gradle
```

Create a symbolic link from /root/.gradle to the new .gradle/ directory we just created (which should have our cached stuff).

```
COPY bin/ /opt/test-runner/bin/
ENTRYPOINT ["sh", "/opt/test-runner/bin/run.sh"]
```

Another English looking copy followed by setting up the entry point pointing to the run.sh file.

**Comment by jmrunkle** [comment]
Now tracing the run.sh file:

```
if [ $# -lt 3 ]
then
    echo "Usage:"
    echo "./bin/run.sh two_fer ~/input/ ~/output/"
    exit 1
fi

problem_slug="$1"
input_folder="$2"
output_folder="$3"
compiler_error_log="compiler.log"
```

Simple usage info, input checking and setting one constant. Makes sure this was called correctly, no real comments here.

FYI: the `two_fer` example is wrong. It would be `two-fer`.

```
cp -r $input_folder /opt/test-runner/lib/$problem_slug
cd /opt/test-runner/lib
```

Copy the folder into lib/$problem_slug (eg. lib/two-fer). This should contain the user's submitted code and the tests now. Then it moves to the parent directory for the exercise slug directory (which is also the parent of buildSrc - where the test runner code is located).

```
find . -mindepth 1 -type f | grep 'Test.java' | xargs -I file sed -i "s/@Ignore(.*)//g;s/@Ignore//g;" file
cat <<EOF >settings.gradle
include '${problem_slug}'
EOF
```

Find all Test.java files and remove the `@Ignore` declarations. Also create a /opt/test-runner/lib/settings.gradle file which includes the exercise slug.

```
gradle --offline addListeners compileJava compileTestJava 2> /tmp/$compiler_error_log
```

Now we compile the code from our current working directory (/opt/test-runner/lib/) and use addListeners which comes from the build.gradle file that is in that directory (copied there in the Dockerfile from [here](https://github.com/exercism/java-test-runner/blob/main/lib/build.gradle)).

My question is why this would not re-trigger compilation of this code: https://github.com/exercism/java-test-runner/blob/main/lib/build.gradle#L7-L14? That looks like it should re-run the annotation processor which is probably a somewhat lengthy process since it has to look at all files checking for the annotations.

**Comment by jmrunkle** [comment]
NOTE: the build.gradle for the buildSrc directory also has this lombok dependency: https://github.com/exercism/java-test-runner/blob/main/lib/buildSrc/build.gradle#L10

**Comment by ErikSchierboom** [comment]
> My question is why this would not re-trigger compilation of this code: https://github.com/exercism/java-test-runner/blob/main/lib/build.gradle#L7-L14? That looks like it should re-run the annotation processor which is probably a somewhat lengthy process since it has to look at all files checking for the annotations.

Ah, I think I'm now starting to understand the issue a bit better. Am I correct in interpreting this as:

The test runner is compiled with the exercise's source code alongside it? If so, this would definitely explain why it is slow. I would have expected something like the Kotlin test runner, where the test runner itself is [compiled once in the Dockerfile](https://github.com/exercism/kotlin-test-runner/blob/main/Dockerfile#L13) and then [this pre-built jar is run for each solution](https://github.com/exercism/kotlin-test-runner/blob/main/bin/run.sh).

**Comment by jmrunkle** [comment]
Agreed, that seems like a much better way to do it. Unfortunately, I think the way it is currently written totally relies on that way of doing things (leveraging Gradle's ability to [add listeners](https://github.com/exercism/java-test-runner/blob/main/lib/build.gradle#L17-L21)).

I guess we have to use gradle test to produce a report (I think it can make an HTML or XML report).

**Comment by ErikSchierboom** [comment]
@jmrunkle I think that would make a lot of sense. I'm fairly sure gradle can output an XML report (JUnit format IIRC).

**Comment by jmrunkle** [comment]
> @jmrunkle I think that would make a lot of sense. I'm fairly sure gradle can output an XML report (JUnit format IIRC). Would you be interested in working on this?

Sure, it will just take a bit of work to get it into a usable state. I can do some playing around with it today and see how far I can get.

**Comment by ErikSchierboom** [comment]
Excellent! Just to be clear: there are three different versions of [the test runner interface](https://exercism.org/docs/building/tooling/test-runners/interface) that can be implemented, each one adding features to the previous version. The v1 spec should actually be very simple to implement, but it might be relatively easy to support the v2 spec with a JUnit report (you could ignore the `test_code` field for now and add that later).

**Comment by jmrunkle** [comment]
Just all of the infra stuff to get it to run the jar in docker and still have the junit deps working in offline mode. I'm working on it in a draft PR. Maybe within a week I can have something that implements the v1 spec and I can fast follow on getting a v2 with aspirations on a v3 version.

**Comment by jmrunkle** [comment]
Getting close now. I have it parsing an xml file and reporting the errors. Still need to wire up reporting on compiler errors and actually setup running the real Gradle test. I may even be able to go for gold and have it parse the actual test file contents so that we can actually have version 2 support right away. This should be much faster since it will only compile the actual code and tests for the exercise.

**Comment by jmrunkle** [comment]
Sent #30 out for review which I believe should do much better for us. It certainly has a better separation of concerns (the test runner source is compiled into a JAR and then we use that JAR to compile and run the tests). It may be absolutely incomprehensible garbage to someone else reading this, but I tried to make it somewhat readable. We can review / discuss improvements over in the PR.

**Comment by masahx** [comment]
happened same for Lasagna for me, after three spaces in editor it passed >D

**Comment by ErikSchierboom** [comment]
With #33 merged, I can now get passing tests on lasagna. It's still slow and could use more work to speed it up, but it is at least working for now.

**Comment by masahx** [comment]
hi, 
again, tests passed on my computer (with OK test duration), didn't pass here...
![image](https://user-images.githubusercontent.com/8939036/135804269-3800b3c2-0302-45e9-9afa-4daba2e0f294.png)

Exercism says: Please check your code, and if nothing seems to be wrong, try running the tests again.

- I can't run tests again for this iteration, I can only open editor, which copies this solution, which makes another iteration? And run tests there?

**Comment by mirkoperillo** [comment]
Thank you @masahx for your advisory. We'll analyze the problem ASAP

**Comment by masahx** [comment]
hey, tests started to pass now, next Iterations went fine. I wrote that on some other thread too
