### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/java-test-runner#34]
There should be tests to verify the test runner behavior. The best option is probably to mimic what other tracks are doing, and having a `tests` directory with some golden tests (see https://github.com/exercism/prolog-test-runner/tree/main/tests) and then having a [`bin/run-tests.sh`](https://github.com/exercism/prolog-test-runner/blob/main/bin/run-tests.sh) and [`bin/run-tests-in-docker.sh`](https://github.com/exercism/prolog-test-runner/blob/main/bin/run-tests-in-docker.sh] script files. These are then used in a [CI workflow](https://github.com/exercism/prolog-test-runner/blob/main/.github/workflows/ci.yml).

**Comment by ericbalawejder** [comment]
Has this issue been addressed?
It looks like the golden tests are here: https://github.com/exercism/java-test-runner/tree/main/tests and the shell scripts are here: https://github.com/exercism/java-test-runner/tree/main/bin

**Comment by ErikSchierboom** [comment]
Correct! This issue should have been closed by #41.
