### ISSUE TITLE
unknown testing error in online editor, while local tests run well

### ISSUE THREAD

**Issue by dchelnokov** [exercism/java-test-runner#54]
Hi, I checked the local tests of the Hello World exercise and they passed ok, but the online test system returns an unknown error
![java_test_runner_at_exercism](https://user-images.githubusercontent.com/19837826/180668822-b7c6c26f-41a1-4e28-a9f4-e5c9ad2e1d53.png)

The code of the exercise that I uploaded:
`class Greeter {
    String getGreeting() {
        return "Hello, World!";
    }
}`
The [instruction ](https://exercism.org/tracks/java/exercises/hello-world) for the excersise "Hello World in Jave" suggest to remove the line 4 that should be listed as follows "_Either working locally or using the online editor, you should find an exception on line 4:_":
`throw new UnsupportedOperationException("Delete this statement and write your own implementation.");`
However, the original listing downloaded using the local "exercism download --exercise..." command doesn't inlclude the line.

The local test file contains the following code:

```
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class GreeterTest {

    @Test
    public void testThatGreeterReturnsTheCorrectGreeting() {
        assertThat(new Greeter().getGreeting()).isEqualTo("Hello, World!");
    }

}
```

and it allows to pass the test (locally). A peer of mine who did this independent from me confirmed the same issue.
Maybe someone could help us out? :)
Thanks in advance.

**Comment by andrerfcsantos** [comment]
@dchelnokov Thanks for opening this!

There seems to be two issues here: the tests not passing and the instructions not being accurate. Let's tackle them separately.

About the instructions not being accurate, I created https://github.com/exercism/java/issues/2151, let's discuss the issue there instead. Feel free to submit a PR in the exercism/java repo fixing it (or anyone else, of course :)). Let's discuss the instructions in that issue and not on this one.

About the tests not passing in the online editor, can you run the tests again and confirm you are still seeing the error? We did have a problem with the test runner a few days ago, but that should be fixed now. Running the tests again should do the trick, let me know if it doesn't. I ran your solution in the online editor and it is passing for me.

**Comment by dchelnokov** [comment]
@andrerfcsantos , thank you for replying:)
The issue in the online editor seems to got resolved for me - fantastic!

I will join to the work on the issue #2151 you mentioned asap. 
thanks a lot again.
