### ISSUE TITLE
Add support for parameterized tests

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java-test-runner#72]
Currently we cannot use parameterized tests in JUnit, probably because the test runner is not equipped to match the test methods to the test results.

Using parameterized tests would be an improvements for some practice exercises though, where the canonical data contains test cases that would otherwise result in a lot of duplication. One example of such an exercise is [Killer Sudoku Helper](https://github.com/exercism/problem-specifications/blob/main/exercises/killer-sudoku-helper/canonical-data.json)

**Comment by ssharaev** [comment]
Hi, @sanderploegsma !
I've opened a PR, could you have a look?
Thank you!
